[versions]
agp = "8.1.0"
kotlin = "1.9.0"
core-ktx = "1.10.1"
compose = "1.5.1"
foundation = "1.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
navigation = "2.7.2"
coil = "2.4.0"

[libraries]
material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

